create table if not exists public.osm_sport_centers (
  id bigserial primary key,
  osm_type text not null,
  osm_id bigint not null,
  name text not null,
  sports text[] not null default '{}',
  opening_hours text not null,
  website text not null,
  payment text,
  phone text,
  email text,
  address text,
  street text,
  house_number text,
  postal_code text,
  city text,
  latitude double precision not null,
  longitude double precision not null,
  tags jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (osm_type, osm_id)
);
